"""rename address

Revision ID: 1c8bfce2ba66
Revises: df447366ac5c
Create Date: 2025-01-18 18:42:29.672537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8bfce2ba66'
down_revision = 'df447366ac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('department', 'address')
    op.alter_column('department', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('department', 'location')
    op.alter_column('department', 'address', new_column_name='address')
    # ### end Alembic commands ###
